import { useEffect, useState } from 'react';
import WorkspaceShell from '../components/WorkspaceShell';
import api from '../services/api';

export default function Profile() {
  const [data, setData] = useState(null); const [form, setForm] = useState({ bio: '', location: '', timezone: 'UTC', experience_level: '' }); const [saved, setSaved] = useState('');
  useEffect(() => { api.get('/workspace/profile').then(({ data: value }) => { setData(value); setForm(value.profile); }); }, []);
  async function save(event) { event.preventDefault(); await api.put('/workspace/profile', form); setSaved('Profile saved'); }
  return <WorkspaceShell title="Your profile" eyebrow="Identity"><div className="mt-8 grid gap-6 lg:grid-cols-[0.7fr_1.3fr]">{data && <div className="card p-6"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-ember-100 font-display text-3xl text-ember-800">{data.user.full_name[0]}</div><h2 className="mt-5 font-display text-2xl text-ink-900 dark:text-white">{data.user.full_name}</h2><p className="text-sm text-ink-500">@{data.user.username} · {data.user.email}</p><p className="mt-6 text-sm text-ink-500">{data.skills.length} skills listed · {data.user.skill_credits} credits</p><div className="mt-6 flex flex-wrap gap-2">{data.skills.map((skill) => <span className="rounded-full bg-ink-100 px-3 py-1 text-xs text-ink-700 dark:bg-ink-800 dark:text-ink-200" key={`${skill.type}-${skill.id}`}>{skill.name}</span>)}</div></div>}<form className="card space-y-5 p-6" onSubmit={save}><h2 className="font-display text-2xl text-ink-900 dark:text-white">About you</h2><label className="block text-sm">Bio<textarea className="input-field mt-2 min-h-28" value={form.bio} onChange={(e) => setForm({ ...form, bio: e.target.value })} /></label><label className="block text-sm">Location<input className="input-field mt-2" value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label className="block text-sm">Experience<select className="input-field mt-2" value={form.experience_level} onChange={(e) => setForm({ ...form, experience_level: e.target.value })}><option value="">Choose level</option>{['Student','Early Career','Mid Career','Senior'].map((level) => <option key={level}>{level}</option>)}</select></label>{saved && <p className="text-sm text-green-700">{saved}</p>}<button className="btn-primary">Save profile</button></form></div></WorkspaceShell>;
}
